// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFoEmecYVLp5zDRJiL7WQb7p6KoTxINI',
    appId: '1:198214174263:web:205a51a53f3c8f0f50a1b2',
    messagingSenderId: '198214174263',
    projectId: 'lecturer-con',
    authDomain: 'lecturer-con.firebaseapp.com',
    storageBucket: 'lecturer-con.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTRVBauAholTKcIJfQAnbFp2_p_2V5OVk',
    appId: '1:198214174263:android:c08aaab9a76d58f850a1b2',
    messagingSenderId: '198214174263',
    projectId: 'lecturer-con',
    storageBucket: 'lecturer-con.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQVT8hgwCfLO9MflgNyhtW2NLteflb8Q',
    appId: '1:198214174263:ios:5f89b55e7e710a4850a1b2',
    messagingSenderId: '198214174263',
    projectId: 'lecturer-con',
    storageBucket: 'lecturer-con.appspot.com',
    iosClientId: '198214174263-a24e3ft4m98b5k24dqjt69put3p9olqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLecon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQVT8hgwCfLO9MflgNyhtW2NLteflb8Q',
    appId: '1:198214174263:ios:5f89b55e7e710a4850a1b2',
    messagingSenderId: '198214174263',
    projectId: 'lecturer-con',
    storageBucket: 'lecturer-con.appspot.com',
    iosClientId: '198214174263-a24e3ft4m98b5k24dqjt69put3p9olqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLecon',
  );
}
